-- MySQL Script generated by MySQL Workbench
-- Fri Feb  9 18:53:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userId` INT NOT NULL,
  `userFirstName` VARCHAR(45) NULL,
  `userSurname` VARCHAR(45) NULL,
  `userEmail` VARCHAR(200) NULL,
  `userPassword` VARCHAR(45) NULL,
  `userDeleted` CHAR(1) NULL,
  `userCreatedDate` DATE NULL,
  `userCreatedBy` INT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `projectId` INT NOT NULL AUTO_INCREMENT,
  `projectTitle` VARCHAR(100) NOT NULL,
  `projectType` VARCHAR(100) NULL,
  `projectCommensingDate` DATE NULL,
  `projectCompleteDate` DATE NULL,
  `projectContractor` VARCHAR(200) NULL,
  `projectConsultant` VARCHAR(200) NULL,
  `projectLocation` VARCHAR(200) NULL,
  `projectEstCost` DECIMAL(200) NULL,
  `projectDescription` VARCHAR(1000) NULL,
  `projectPhotos` VARCHAR(500) NULL,
  `createdBy` INT NOT NULL,
  `projectDeleted` CHAR(1) NULL,
  PRIMARY KEY (`projectId`),
  INDEX `fk_Project_User_idx` (`createdBy` ASC),
  CONSTRAINT `fk_Project_User`
    FOREIGN KEY (`createdBy`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `serviceNo` INT NOT NULL AUTO_INCREMENT,
  `serviceTitle` VARCHAR(200) NULL,
  `serviceDesc` VARCHAR(2000) NULL,
  `createdBy` INT NOT NULL,
  `servicePhotos` VARCHAR(500) NULL,
  `serviceDeleted` CHAR(1) NULL,
  PRIMARY KEY (`serviceNo`),
  INDEX `fk_Service_User1_idx` (`createdBy` ASC),
  CONSTRAINT `fk_Service_User1`
    FOREIGN KEY (`createdBy`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Downloads` (
  `fileNo` INT NOT NULL AUTO_INCREMENT,
  `fileType` VARCHAR(45) NULL,
  `fileTitle` VARCHAR(100) NULL,
  `fileAddedDate` DATE NULL,
  `file` VARCHAR(200) NULL,
  PRIMARY KEY (`fileNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Needs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Needs` (
  `needId` INT NOT NULL AUTO_INCREMENT,
  `needTitle` VARCHAR(100) NULL,
  `needDesc` VARCHAR(2000) NULL,
  `createdDate` DATE NULL,
  `needDeleted` CHAR(1) NULL,
  PRIMARY KEY (`needId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Info` (
  `infoNo` INT NOT NULL AUTO_INCREMENT,
  `infoTitle` VARCHAR(100) NULL,
  `infoDetails` VARCHAR(5000) NULL,
  `InfoCreatedDate` DATE NULL,
  PRIMARY KEY (`infoNo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
